# Generated by Django 2.2.2 on 2019-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190709_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
