# Generated by Django 2.2.2 on 2019-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190710_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='display_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
