# Generated by Django 2.2.2 on 2019-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190714_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('college_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['college_name'],
            },
        ),
    ]
