# Generated by Django 2.2.2 on 2019-07-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('project_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('project_link', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(to='accounts.Skill')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
    ]
