# Generated by Django 2.2.2 on 2019-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('volunteer_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['volunteer_name'],
            },
        ),
    ]
