# Generated by Django 2.2.2 on 2019-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('TOOLS', 'Tools'), ('INDUSTRY_KNOWLEDGE', 'Industry Knowledge')], default='TOOLS', max_length=20),
        ),
    ]
