# Generated by Django 2.2.2 on 2019-07-16 06:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=accounts.models.user_upload_to, width_field='width'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=accounts.models.user_upload_to, width_field='width'),
        ),
    ]
