# Generated by Django 2.2.2 on 2019-07-16 07:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190716_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_upload_to),
        ),
    ]
