# Generated by Django 2.2.2 on 2019-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190716_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_image',
        ),
    ]
